# 投资机构数据集探索\n\n读取 `data/investors_final.json`，对 12,000+ 条清洗后的投资机构数据做基础探索。

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
import pandas as pd

# 读取普通 JSON 文件
df = pd.read_json('./data/enrichment_target/enriched.jsonl', lines=True)
df

                         id  \
0          exa_995c191412a5
1          exa_5371fe13531a
2                adv_163421
3          exa_d3515f87d57f
4          exa_35f42e69fc5d
5          exa_6f888630c64d
6          exa_8d5cc1b3e04b
7          exa_b98566dd14f6
8                adv_309041
9          exa_68a4ff5d4ff7
10         exa_4b6c0db9bd3a
11         exa_564b9c2621e3
12         exa_47006c9ecf8f
13         exa_679405befe78
14         exa_c8c3fecd33b8
15         exa_0ecb2a2d1504
16               adv_322999
17         exa_3cbaaa02424b
18         exa_6e5eceaf4380
19               adv_329078
20         exa_ba4def74bfc9
21         exa_251f366c3a1d
22         exa_9fe80505ba71
23         exa_ecbad8465613
24         exa_c48ee3adf405
25         exa_7f265e32a6ce
26         exa_5d16acc58145
27               adv_167165
28         exa_3927ac5c2582
29         exa_747bb16718cb
30               adv_283270
31         exa_1f165ad220c2
32         exa_41151e4320de
33         exa_5735a88b829f
34         exa_67b50a39cb7e
35               adv_293073
36         exa_9c13ea34a473
37         exa_bebb9635aeeb
38         exa_6c3ad0023826
39         exa_10db72a602e5
40         exa_dcd5a7c87008
41         exa_805b7e44f374
42         exa_160ac8c05e8d
43         exa_cfc490a54ea0
44         exa_4153ccc39d73
45         exa_1add06f2be83
46         exa_3e6ce2a434c2
47         exa_0df37216fdcf
48         exa_1d9b6e48a93d
49         exa_30360cf1c0e0
50         exa_d279d2963b5c
51         exa_86289a103509
52               adv_313985
53         exa_c06ef1d5c995
54               adv_210524
55         exa_454fe195e903
56         exa_8feb9e9186dc
57         exa_8b2ac75304b3
58         exa_fc3bab29995c
59         exa_2933b7846a19
60         exa_2eeb430be2de
61         exa_28a6275b7099
62         exa_41922bf6b48d
63         exa_dce7a3dfeb5b
64         exa_8c0f97cb77f4
65         exa_d6fa5adbdf3a
66         exa_0ea39e77a3f9
67         exa_cf0fd453ad42
68         exa_6cf23bed3c36
69         exa_6dc38c2dd9e8
70               adv_120780
71               adv_155425
72         exa_b22ebd4bee71
73         exa_9f4e428d6d42
74         exa_5eb0d1cbcf72
75         exa_7f7b3fa007fe
76         exa_2778e2586833
77         exa_0902cc334942
78         exa_22ce49cc0d95
79         exa_d7ceeee8bbd5
80         exa_7e7ee0ec7dad
81         exa_48ac948bfebd
82         exa_48c7f2639f06
83         exa_f5b2a28d42dc
84         exa_7d97a137f0c9
85         exa_82d3f84d7f89
86         exa_2214a6575c76
87         exa_4be1617e58af
88         exa_a6aac3582bba
89         exa_dc4a83d46cb6
90         exa_889cf846ceb7
91         exa_d8d73c8ad578
92         exa_e185c2dbc3b7
93         exa_32238fa11889
94         exa_de77b627a72e
95         exa_0a9a40778b5b
96         exa_91705606a259
97         exa_d38423d0f4e3
98         exa_70cda834385f
99         exa_77cdbe5d1210
100        exa_c443e3b6b3ac
101        exa_e0138e0751ee
102        exa_4f79e9a6b05e
103        exa_5a8c8c78fff5
104        exa_663a913b3fbc
105        exa_7fcad29b0576
106        exa_0adb955836a8
107        exa_832b81345ae7
108        exa_7bcb11a15fa0
109        exa_ddb6d6aace7c
110        exa_f6c5218b4538
111        exa_f1678134fed2
112        exa_a146b147d431
113        exa_938b59e7bd63
114        exa_8c573eed8a6a
115        exa_5aa2b1b201af
116        exa_ced88c5651e2
117        exa_48452eccf4ca
118        exa_a5b293ce53ad
119        exa_2110b6e3e016
120        exa_736c3d2b337e
121        exa_4f4e45679618
122        exa_5d3836090e6f
123        exa_ea1f42202336
124        exa_14f8180e425d
125        exa_11d168b72bf6
126        exa_75f913ae214c
127        exa_da75a9a4d70a
128              adv_145653
129              adv_331368
130              adv_281082
131              adv_309047
132              adv_312887
133              adv_156961
134              adv_139256
135              adv_288774
136              adv_161422
137              adv_285024
138              adv_160187
139              adv_285990
140              adv_311351
141              adv_160561
142              adv_333573
143        exa_97a553262ce6
144              adv_281620
145        exa_bd60aad5e97c
146        exa_cf0077eec2e9
147        exa_f7d567d3b8a3
148        exa_7340c90aa028
149        exa_a654261c2d47
150        exa_2689794d25ef
151        exa_822db808a7d0
152        exa_de23b6a360c4
153        exa_74f5f3331602
154        exa_7242978ea0a4
155        exa_e9c3b804938d
156        exa_b3e4886fdb08
157        exa_98b7831f9980
158        exa_9f06ed1a6c56
159        exa_54372cc68f1d
160        exa_966cf16870c7
161        exa_b675393ac27b
162        exa_74ef09332093
163        exa_f27c5725af40
164        exa_d5b84e171ebb
165        exa_d41c4a01b882
166        exa_ba7830511eed
167        exa_3d9e0cec848b
168        exa_dfc76ec51102
169        exa_f33dd61cb0d2
170        exa_b7f009a473db
171        exa_30be953dba5c
172        exa_ccdbce800abc
173        exa_d58a214f056e
174        exa_f30692aaaf8c
175        exa_bcdd2f585036
176        exa_b7d1df2c5643
177        exa_b2c7a5b743f9
178        exa_705eb627bc54
179        exa_c2740c05c720
180        exa_f50db4ffa802
181        exa_f406260d3011
182        exa_be160c037491
183        exa_a4275d65d2c8
184        exa_271cec6630c7
185        exa_eaa98cbaf5dc
186        exa_f8f3b3e1e6c4
187        exa_8e7b3f569586
188        exa_8f083a9fb8bd
189        exa_f02d069c5940
190        exa_25499f0db57f
191        exa_b0077a72cb83
192        exa_3abdc896eb63
193        exa_c724adfae8ab
194        exa_c0e99291cd0b
195        exa_3117baaa9620
196        exa_d3e7e9555783
197        exa_5e8fef008c9d
198        exa_9f83d88c7cad
199        exa_a3c677415f98
200        exa_94135f2bf519
201        exa_382f381848b9
202        exa_241187f7ba24
203        exa_b6d75facfc36
204        exa_36ef94874352
205        exa_c84dc998fe28
206        exa_82e5e223270d
207        exa_5b1ab3a18abf
208        exa_cd3d69b64a95
209        exa_67f6a4c65070
210        exa_87a33ae2712c
211        exa_b72e7e5785e6
212        exa_7e209f1d58e1
213        exa_21b6a7aec422
214        exa_545ad9fc7d7a
215        exa_50421bf0d275
216        exa_b32b74ab1e0e
217        exa_3aa532f158e5
218        exa_68936c97a2c5
219        exa_c9fc508bc551
220        exa_e84deed6f154
221        exa_bed11d1d6c1b
222        exa_04fcaa5542cb
223              adv_161684
224              adv_172012
225              adv_283262
226              adv_116165
227              adv_160483
228              adv_164429
229              adv_165915
230              adv_339223
231              adv_283031
232              adv_173709
233              adv_163489
234              adv_293329
235              adv_133792
236              adv_171612
237              adv_158494
238              adv_281928
239              adv_161059
240              adv_290082
241              adv_304461
242              adv_160075
243              adv_335324
244              adv_293249
245              adv_300968
246              adv_156861
247              adv_315967
248              adv_156909
249              adv_290282
250              adv_168496
251              adv_307713
252              adv_322344
253              adv_170880
254              adv_140522
255              adv_317369
256              adv_155953
257              adv_319671
258        exa_25f686b256fd
259        exa_551998c753b4
260        exa_2597d066a8c6
261        exa_91617bdf36e1
262        exa_0ad9d0244b75
263        exa_5dd112364c43
264        exa_cb4fbef8ecbb
265        exa_e3d8f80cf098
266        exa_7a639d55698e
267        exa_4c6295a9bec7
268        exa_8b0fdde2e89a
269        exa_2af1fb7e3ff0
270        exa_69ff5e989260
271        exa_80626ac85f25
272        exa_3eae081eb05a
273        exa_3846b2d8934f
274        exa_dbbdec47e692
275        exa_d6ed8ed0447f
276        exa_88f199b21fd3
277        exa_d62b0770b6fc
278        exa_f7cd0760195d
279        exa_7de453283135
280        exa_14e7866f66a1
281        exa_5ccea4674aa7
282        exa_02e366df476a
283        exa_fbff90764b57
284        exa_f8ea5115a775
285        exa_a631fdf91da9
286        exa_51c994161581
287        exa_043e124e5bd8
288        exa_b4a3d42ea7cc
289        exa_65f1d12152e7
290        exa_9a1153cebb42
291        exa_de077a64fc61
292        exa_e88ec3f26c22
293        exa_43bea7f0e6e0
294        exa_c01ac80f5a75
295        exa_de34798924dd
296        exa_1dfdb53f31bd
297        exa_622b4f7963ca
298        exa_b65739ddbeba
299        exa_fd8f9aa42d2c
300        exa_688ebc4ca591
301        exa_c6a8d4c06cd8
302        exa_457d9a8db138
303        exa_502c77626553
304        exa_e655785894fd
305        exa_91ee658baed0
306        exa_9620e8ecf951
307        exa_7b77e5bfa4af
308        exa_96695b9cb18b
309        exa_57f04b34b913
310        exa_deaa26b42f5f
311        exa_40c080f8c299
312        exa_9ea7f1387523
313        exa_0541255a3727
314        exa_79820db73190
315        exa_8a5dbf535b38
316        exa_e7157cbae494
317        exa_8ee511f7564a
318        exa_6ba52af586c4
319        exa_350febe2f7f6
320        exa_c4bc102208fb
321        exa_7143978fe3de
322        exa_b1a36721f6a3
323        exa_902cf2f429ba
324        exa_548f6ec5837a
325        exa_51698d9499a2
326        exa_4c01692ba018
327        exa_e1f673e71dcd
328        exa_9d81e519c17e
329        exa_650534c9b3e9
330        exa_f71e41c237de
331        exa_4c9ad9d37e70
332        exa_61c56e01aceb
333        exa_19559930aaf9
334        exa_c66697b131bc
335        exa_4ef41118f4b9
336        exa_a763cf6dee46
337        exa_d94e8c0468b5
338        exa_7bc4a5fb0d72
339        exa_93d88f680aed
340        exa_86f69b669ba1
341        exa_0cfa94577a24
342        exa_9cf39b98da65
343        exa_3e8d7fae55cf
344        exa_dfa7fa170bcc
345        exa_47c4b11c3c7e
346        exa_3e197020c455
347        exa_d2829b1f766e
348        exa_fe0c5376ff2b
349        exa_cf8ff2c84c41
350        exa_08f1b15fc003
351        exa_01896d78f64f
352        exa_40be4e59b9a2
353        exa_2056a4c366f5
354        exa_a667992171db
355        exa_8db8f6c3867c
356        exa_bc2b800fda22
357        exa_ba1c8e2db0cc
358        exa_ed226db1c971
359        exa_c9e8d36008f3
360        exa_b1ae62f3592d
361        exa_2a0b480fb10a
362        exa_164dfd8c15b0
363        exa_fea320dafed9
364        exa_3eded3fd7cf1
365        exa_bb643583d005
366        exa_b0fc446dc170
367        exa_acb00511c4e8
368        exa_727fa2d1e43b
369        exa_42491d17dbc0
370        exa_32dc46d118a3
371        exa_60d90904ed93
372              adv_173136
373              adv_173735
374              adv_309949
375              adv_311479
376              adv_160750
377              adv_304477
378              adv_283812
379              adv_157559
380              adv_157622
381              adv_157324
382              adv_282387
383              adv_311770
384              adv_317522
385              adv_296583
386              adv_170956
387              adv_291881
388              adv_300701
389              adv_146747
390              adv_310044
391              adv_302116
392              adv_286213
393        exa_370f39c50be8
394              adv_294006
395              adv_315069
396              adv_161235
397              adv_339275
398              adv_285151
399              adv_335443
400              adv_162712
401              adv_160311
402        exa_c3e4d84a2b69
403        exa_23aae460bf8d
404        exa_bbd9b358e219
405        exa_acc83b3251b7
406        exa_a4bd71ede6a0
407        exa_3e7c0ee22519
408        exa_e98adf19c874
409        exa_bee23fff35d9
410        exa_81c4825dcaca
411        exa_c0eb62dce952
412        exa_7bc764bd87ca
413        exa_dcbc201f4751
414        exa_9aef46199c88
415        exa_77d9582d5be2
416        exa_22c1923d6740
417        exa_6f89ad118e42
418        exa_49412ce629c7
419        exa_1d496026dac7
420        exa_0674ec5322b4
421        exa_acec02f3ed28
422        exa_1002c0e195ca
423        exa_4ebefbc26474
424        exa_41536ecd93df
425        exa_609480a1d1eb
426        exa_ab1f0d1d7910
427        exa_5ab9e7e9b30e
428        exa_276670feb299
429        exa_75e505977fbe
430        exa_802aa297344b
431        exa_259b1f839163
432        exa_28d4d48c498b
433        exa_6423c6e0e0d9
434        exa_aaf81ba43924
435        exa_839200b72abd
436        exa_05199deca166
437        exa_ef83242f2426
438        exa_90c3a81803e6
439        exa_f1785329bed5
440        exa_01c5569fa5a1
441        exa_cae4ebe0026f
442        exa_466dce02b4a6
443        exa_86dc4594c3aa
444        exa_1ba76e5a3775
445        exa_9cdf526024bd
446        exa_97cc25d4adbb
447        exa_e1f7d5252b1c
448        exa_44cd18b45a74
449        exa_6c6bdf629a82
450        exa_169b1dbd4f7c
451        exa_aeaf78ac4cb0
452        exa_c98653d341f3
453        exa_bbb769cc71e5
454        exa_f9794c6a3a25
455        exa_7fcbcd0d8a7b
456        exa_96f324cc3b32
457        exa_79ab5f77c8de
458        exa_b0a4b472993a
459        exa_db4831a50fe6
460        exa_e426c2cedb9f
461        exa_e4774c00d1f7
462        exa_149e5af51196
463        exa_bd310d87c1b1
464        exa_9796c454cd82
465        exa_15d577f405c3
466        exa_fac5e131ad77
467        exa_594b15fc4868
468        exa_c0a63d90906c
469        exa_e22169b2d5ff
470        exa_1e579b280d30
471        exa_ebad535fd655
472        exa_e4dc13b3844e
473        exa_2c7030ae2f1d
474        exa_6a3391fd0c7b
475        exa_64ef1473cd7d
476        exa_9a0c02acffda
477        exa_475c95d73066
478        exa_1c3c35572213
479        exa_530d26969bbe
480        exa_c20e973c76c5
481        exa_4ee1a0307bc6
482        exa_64d64a16b4cd
483        exa_4989447faff0
484        exa_a0177750a2db
485        exa_883e9b0103de
486        exa_9e1880538d74
487        exa_dc39231af95e
488        exa_aec4f6e41436
489        exa_cc64bcb7383e
490        exa_f2b18e713beb
491        exa_9abccb1fb5f3
492        exa_2a81afc7fcd5
493        exa_9bff5152c50d
494  split_exa_49412ce629c7

                                                  name  is_real_investor  \
0                                              AccelR8              True
1                                   NewHealth Ventures              True
2                       Healthedge Investment Partners              True
3                                   Lionheart Ventures              True
4                                  TechSquare Ventures              True
5                                    Eminence Ventures              True
6                                         Ada Ventures              True
7                    Deep-Tech AI Seed Venture Capital              True
8                   Healthpointcapital Management, Llc              True
9                                    NextStep Ventures              True
10                                                DCVC              True
11                                    Healthy Ventures              True
12                           Holman Strategic Ventures              True
13                             Runway Venture Partners              True
14                                Cooperative Ventures              True
15                                  Water & Wastewater              True
16                         Caymus Equity Partners, Llc              True
17                                    Insight Partners              True
18                                  Earthshot Ventures              True
19                                   Connetic Ventures              True
20                               Yamaha Motor Ventures              True
21                                10X Venture Partners              True
22                                            Costanoa              True
23                                       EcoR1 Capital              True
24                                      Humba Ventures              True
25                                     Better Ventures              True
26                                                D4ir              True
27                     Consonance Capital Partners, Lp              True
28                  Why Invest with Nucleation Capital              True
29                                        5AM Ventures              True
30                 Csc Upshot Ventures Management, Llc              True
31                                       INAYA Capital              True
32                               Beyond Earth Ventures              True
33                                     Engine Ventures              True
34                                             AI Seed              True
35                                  Dc Global Ventures              True
36                                         ExO Capital              True
37                            Wildcat Venture Partners              True
38                               Core SV Biotech Funds              True
39                  Leaders in Clean Energy Investment              True
40                                   Sovereign AI Fund              True
41                                        ALM Ventures              True
42                                      Llama Ventures              True
43                                           NVentures              True
44                                  Starlight Ventures              True
45                                  Starburst Ventures              True
46                                    Act One Ventures              True
47                                        Talents Fund              True
48                                   Longitude Capital              True
49            Deep Tech Infrastructure & Autonomy Fund              True
50                                     Arteria Capital              True
51                                      Venture Equity              True
52              Alterna Equity Partners Management Llc             False
53                                  Next Gear Ventures              True
54                              Ancor Capital Partners              True
55                            Democratizing Investment              True
56                                       2048 Ventures              True
57                                Evio Venture Capital              True
58                          Capricorn Investment Group              True
59                                    Felicis Ventures              True
60                                Echo Health Ventures              True
61                                    Generate Capital              True
62                                    IA Capital Group              True
63                                      Index Ventures              True
64                            Lobdell Venture Partners              True
65                                 Multimodal Ventures              True
66                                          ND Capital              True
67                                  Schematic Ventures              True
68                                 Unshackled Ventures              True
69                                      Qbeat Ventures              True
70                            Bonaventure Capital, Llc              True
71                         Truebridge Capital Partners              True
72                                         120 Capital              True
73                               ARCH Venture Partners              True
74                                  Bold Brain Capital              True
75                                         BAI Capital              True
76                                          CVS Health              True
77               Cedars-Sinai and Intermountain Health              True
78                                 Cybernetix Ventures              True
79                                       Longwood Fund              True
80                                First Spark Ventures              True
81                  Investment led by Prime Movers Lab              True

In [14]:
df["thesis_text"][0]

'At Unshackled, we\'ve always started from a simple conviction. If immigrant founders had the freedom to build from day zero, they would create a different kind of company and a different kind of economy. Eleven years in, that\'s no longer just a belief; it\'s actual proof. We are sector agnostic. Like most VCs, we look to invest in founders building companies that can grow at a "venture scale" in large market opportunities. We are conviction driven investors who are comfortable taking on a similar risk as the entrepreneurs. We prefer leading, make our own decisions, and don\'t wait for anyone else. Many entrepreneurs call us their sustainable "friends & family" round. We work with the founders on terms that make the most sense. We want to invest as close to company formation if not earlier. We like to make our initial investment as soon as the founders have the conviction to invest 100% of their energy into the company — "day 0". Often, founders incorporate their company alongside our investment (and we guide on matters that affect founders who are in the US on a visa). We look to lead pre-seed rounds less than $1,000,000 and concentrate on founders that have a strategy for their pre-seed round to last 12–18 months, if not more.'

In [15]:
import pandas as pd

# 读取普通 JSON 文件
df = pd.read_json('./data/enrichment/enriched.jsonl', lines=True)

In [12]:
df["description"][0]

'WorldQuant Ventures\n\nWelcome to WorldQuant Ventures!\n\n# Committed to long-term partnerships for success.\n\nWorldQuant Ventures LLC, founded by Igor Tulchinsky, seeks to invest in innovative entrepreneurs who are driving emerging technologies to bring real world change. Focused on financial technology'

In [16]:
import json
import pandas as pd

# 读取 JSON 文件
with open("data/investors_final.json", encoding="utf-8") as f:
    raw = json.load(f)

# 自动检测 JSON 结构：列表 or 字典
if isinstance(raw, list):
    df = pd.DataFrame(raw)
elif isinstance(raw, dict):
    # 尝试常见的包装键
    for key in ("data", "investors", "records", "results"):
        if key in raw:
            df = pd.DataFrame(raw[key])
            break
    else:
        df = pd.DataFrame([raw])
else:
    raise ValueError(f"不支持的 JSON 结构: {type(raw)}")

print(f"✅ 数据加载完成，共 {len(df):,} 条记录，{df.shape[1]} 列")

✅ 数据加载完成，共 12,102 条记录，31 列

## 1. 基本信息：shape、列类型、前 5 行

In [4]:
df['website'].isnull().sum()

np.int64(653)

In [17]:
df[df['website'].isnull()].head()

,id,name,slug,investor_type,sector,sectors,stage,focus,region,hq_country,hq_state,hq_city,aum_usd,aum_display,check_size_min_usd,check_size_max_usd,check_size_display,website,sec_filing_url,key_people,contacts,portfolio,description,founded_year,sec_crd,sec_file_num,data_source,data_confidence,us_verified,scraped_at,completeness_score
308,exa_04fcaa5542cb,Health Velocity Capital,health-velocity-capital,VC,semiconductor,"[semiconductor, healthcare]",[],"[GaN, health insurance]",North America,US,CA,San Francisco,NaN,NaN,None,None,None,NaN,NaN,[],[],"[Teladoc Health, Tivity Health]",Venture capital firm focused on healthcare tec...,2017.0,NaN,NaN,exa_directory,medium,True,2026-05-02T16:38:10Z,62
309,exa_ff41dbf67824,Presence Capital,amitt-mahajanpresence-capital,VC,semiconductor,[semiconductor],[Angel],[GaN],North America,US,CA,San Francisco,NaN,NaN,None,None,None,NaN,NaN,[],[],"[Carnivore Inc, Carnivore Inc.]",Venture capital firm investing in virtual reality,2012.0,NaN,NaN,exa_directory,medium,True,2026-05-02T16:14:14Z,62
646,exa_4a576f718e22,FJ Labs,fj-labs,VC,edtech,[edtech],[],[],North America,US,NY,New York,NaN,NaN,None,None,None,NaN,NaN,[],[],[FJ Labs],Venture capital firm investing in tech startups,2015.0,NaN,NaN,exa_directory,medium,True,2026-05-02T16:43:18Z,55
647,exa_c97856525a6b,AU21 Capital,au21-capital,Hedge Fund,fintech,[fintech],[],[blockchain],North America,US,CA,San Francisco,NaN,NaN,None,None,None,NaN,NaN,[],[],[],Cryptocurrency hedge fund,2017.0,NaN,NaN,exa_directory,medium,True,2026-05-02T16:46:34Z,54
672,exa_7f0bad312f70,MS&AD Ventures,msad-ventures,Corporate VC,fintech,[fintech],[],"[fintech, insurtech]",North America,US,CA,Menlo Park,NaN,NaN,None,None,None,NaN,NaN,[],[],[],Insurance-focused corporate VC,2018.0,NaN,NaN,exa_directory,medium,True,2026-05-02T16:45:37Z,54

In [19]:
import pandas as pd
import ast

import numpy as np

all_sectors = pd.Series(
    np.concatenate(df['sectors'].values)
).unique()

print(all_sectors)

<StringArray>
[  'ai_hardware',    'healthcare', 'semiconductor',        'energy',
       'fintech',       'ai_apps',        'edtech',     'greentech',
       'general']
Length: 9, dtype: str

## 2. 缺失值统计

In [3]:
# 每列缺失值数量和占比
missing = pd.DataFrame({
    "缺失数量": df.isnull().sum(),
    "缺失占比(%)": (df.isnull().mean() * 100).round(1),
})

# 只显示有缺失的列，按缺失量降序排列
missing_only = missing[missing["缺失数量"] > 0].sort_values("缺失数量", ascending=False)

print(f"共 {len(missing_only)} 列存在缺失值（总列数 {df.shape[1]}）\n")
missing_only

共 13 列存在缺失值（总列数 31）

                     缺失数量  缺失占比(%)
check_size_min_usd  12102    100.0
check_size_max_usd  12102    100.0
check_size_display  12102    100.0
founded_year        11850     97.9
hq_city             11629     96.1
description         11307     93.4
aum_usd               795      6.6
aum_display           795      6.6
sec_filing_url        795      6.6
sec_crd               795      6.6
sec_file_num          795      6.6
website               653      5.4
hq_state              322      2.7

## 3. 字符串列：唯一值数量 ／ 数字列：基本统计

In [4]:
# 按列类型分开处理
str_cols = df.select_dtypes(include="object").columns.tolist()
num_cols = df.select_dtypes(include="number").columns.tolist()

# ── 字符串列：唯一值数量 + Top-5 高频值 ──────────────────────────────────
print(f"══ 字符串列（共 {len(str_cols)} 列）══\n")
str_summary = []
for col in str_cols:
    n_unique = df[col].nunique()
    top_vals = df[col].value_counts().head(5).index.tolist()
    str_summary.append({
        "列名": col,
        "唯一值数": n_unique,
        "Top-5 高频值": ", ".join(str(v) for v in top_vals),
    })

str_df = pd.DataFrame(str_summary).set_index("列名")
print(str_df.to_string())

print()

══ 字符串列（共 27 列）══

/var/folders/zr/skhny4ms03g3n10pdcct6s5w0000gn/T/ipykernel_30146/2315284896.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = df.select_dtypes(include="object").columns.tolist()

TypeError: unhashable type: 'list'

In [ ]:
# ── 数字列：mean / min / max / 非空数量 ──────────────────────────────────
print(f"══ 数字列（共 {len(num_cols)} 列）══\n")
if num_cols:
    num_stats = df[num_cols].agg(["count", "mean", "min", "max"]).T
    num_stats.columns = ["非空数量", "均值", "最小值", "最大值"]
    num_stats["均值"]  = num_stats["均值"].round(2)
    print(num_stats.to_string())
else:
    print("（无数字列）")